### ISSUE TITLE
Replace DataSets by OpenFemaDataSets

### ISSUE THREAD

**Issue by ivanrdgz** [FEMA/openfema-samples#5]
On the final example for pulling just updated records, in the function checkDatasetStatus, the reference to the Json result jsonData['DataSets'][0]['lastDataSetRefresh'] it seems it should be replaced by jsonData['OpenFemaDataSets'][0]['lastDataSetRefresh']

**Comment by lukelamar** [comment]
Thank you! It has been fixed. Backstory - OpenFemaDataSets is an alias of DataSets. During review of the notebook, an editor suggested we replace "DataSets" with "OpenFemaDataSets" to align with the title of the dataset web page on fema.gov. I quickly changed that one instance without testing. Thanks again for the catch!
